version: '3.9'
services:
  db:
    image: mysql:latest
    container_name: springboot-db
    environment:
      MYSQL_ROOT_PASSWORD: Secr3tPassw0rd!
      MYSQL_DATABASE: springboot
      MYSQL_USER: spring
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-config:/etc/mysql/conf.d
volumes:
  db_data: